# https://docs.docker.com/guides/angular/containerize/
server {
    listen 80;
    server_name _;

    # Path to compiled Angular production files
    root /usr/share/nginx/html;
    index index.html;

    # Kompresija (manji transfer za JS/CSS)
    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    # Static Assets Caching
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    # Essential SPA fallback routing logic: sve nepostojece rute idu na index.html (Angular router preuzima)
    # index.html se NE kesira da bi novi deploy odmah bio vidljiv.
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    # /api ne rutiramo, u klasteru će to raditi ingress (same-origin)
    # Za pokretanje kontejnera samostalno potreban je proxy ka backendu i tad treba odkomentarisati location /api/
    location /api/ {
        proxy_pass http://library-be:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
