# https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images
name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build (Angular)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: library-fe-dist
          path: dist/library-fe/browser
          if-no-files-found: error
          retention-days: 3
